version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: root
  flaskapp:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - "db"
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      USE_POSTGRES: strue
    restart: always